apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    cpaas.io/creator: admin@cpaas.io
    cpaas.io/operator: admin@cpaas.io
  labels:
    asm.cpaas.io/msname: upload-file-demo
    msname: upload-file-demo
  name: upload-file-demo
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      service.cpaas.io/name: deployment-upload-file-demo
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cpaas.io/creator: admin@cpaas.io
        sidecar.istio.io/inject: "true"
        sidecar.istio.io/logLevel: warning
        sidecar.istio.io/proxyCPULimit: "0.1"
        sidecar.istio.io/proxyMemoryLimit: 128Mi
      creationTimestamp: null
      labels:
        app: upload-file-demo
        asm.cpaas.io/msname: upload-file-demo
        msname: upload-file-demo
        service.cpaas.io/name: deployment-upload-file-demo
    spec:
      containers:
      - image: build-harbor.alauda.cn/test/upload-file-demo:v1.0.0
        #image: maying0104/upload-file-demo:v1.0.0
        imagePullPolicy: IfNotPresent
        name: upload-file-demo
        ports:
        - containerPort: 8080
          name: http-8080
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 200m
            memory: 200Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30