apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    msname: go-httpbin
  name: go-httpbin
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      project.cpaas.io/name: ym
      service.cpaas.io/name: deployment-go-httpbin
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cpaas.io/creator: admin@cpaas.io
        sidecar.istio.io/logLevel: warning
        sidecar.istio.io/proxyCPULimit: "0.1"
        sidecar.istio.io/proxyMemoryLimit: 128Mi
      creationTimestamp: null
      labels:
        app: go-httpbin
        project.cpaas.io/name: ym
        service.cpaas.io/name: deployment-go-httpbin
    spec:
      containers:
      - args:
        - -c
        - /bin/go-httpbin -port 80 -response-delay 10ms
        command:
        - /bin/sh
        image: maying0104/go-httpbin:1.2-alpine3.13
        imagePullPolicy: IfNotPresent
        name: go-httpbin
        ports:
        - containerPort: 80
          name: http-80
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 200m
            memory: 200Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30