apiVersion: v1
kind: Service
metadata:
  annotations:
    cpaas.io/creator: admin@cpaas.io
    cpaas.io/operator: admin@cpaas.io
    resource.cpaas.io/reference: '["Deployment.upload-file-demo-without-sidecar"]'
  name: upload-file-demo-without-sidecar
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http-8081-8080
    port: 8081
    protocol: TCP
    targetPort: 8080
  selector:
    service.cpaas.io/name: deployment-upload-file-demo-without-sidecar
  sessionAffinity: None
  type: ClusterIP